### ISSUE TITLE
Merge TiFeatures and TiMVT

### ISSUE THREAD

**Issue by bitner** [developmentseed/tipg#1]
Initial checklist for Merging TiFeatures and TiMVT into TiPG

TiPG is intended to merge the features of TiFeatures and TiMVT into a project in order to reduce duplication between the two projects.

- [x] Fork TiFeatures into TiPG
- [x] Rename directories and references in code from tifeatures to tipg
- [x] Rename environment variables from TIFEATURES to TIPG
- [x] Make sure TiFeatures Tests Pass
- [x] Move basic Table layers from TiMVT to TiPG
- [x] Move TMS endpoints from TiMVT to TiPG
- [x] Cherry Pick Functions work from https://github.com/developmentseed/tifeatures/pull/70 
- [ ] Add tests for using Functions
- [x] Update documentation to change references from TiFeatures to TiPG
- [x] Move documentation from TiMVT and update to reference TiPG
- [x] Make sure that endpoints for combined OGC Features / OGC Vector Tiles matches most recent OGC spec
- [x] Make sure that all dependencies (including dev, test) are included and up to date

**Comment by vincentsarago** [comment]
@bitner I think the last missing piece is custom function support. 

### TODO
- add `from_file` class method to `tipg.dbmodel.Collection`: https://github.com/developmentseed/timvt/blob/ff1fc0cdec5a4bc526dfdb8cbf76e4f62a3cf94c/timvt/layer.py#L252-L258
- Register function to the collection_catalog
- add `transaction` to register/deregister the function to the database https://github.com/developmentseed/timvt/blob/ff1fc0cdec5a4bc526dfdb8cbf76e4f62a3cf94c/timvt/layer.py#L276-L308
- update https://github.com/developmentseed/tipg/tree/main/tests/fixtures/functions
- ...

**Comment by bitner** [comment]
> @bitner I think the last missing piece is custom function support.
> 
> ### TODO
> * add `from_file` class method to `tipg.dbmodel.Collection`: https://github.com/developmentseed/timvt/blob/ff1fc0cdec5a4bc526dfdb8cbf76e4f62a3cf94c/timvt/layer.py#L252-L258
> * Register function to the collection_catalog
> * add `transaction` to register/deregister the function to the database https://github.com/developmentseed/timvt/blob/ff1fc0cdec5a4bc526dfdb8cbf76e4f62a3cf94c/timvt/layer.py#L276-L308
> * update https://github.com/developmentseed/tipg/tree/main/tests/fixtures/functions
> * ...

I don't actually like the file based function support. The "idea" of this library (at least to me) is that it never writes/changes anything in the database and that you should manage tables/functions directly in the database. My opinion (not strongly held, so definitely willing to consider the file based functions) is that TiPG should be able to fully run as a Read Only user (this would change if we add transaction support to tables). Ideally, for security, the user that TiPG connects as should not have the ability (even if we add transaction support) to create/drop any new tables/views/functions. I know that this will hardly ever be the case and most people will just be deploying using an admin user, but I'd still like to see us encouraging that best practice and the file based functions runs counter to that.
